kind: pipeline
name: minecraft-bedrock-server

steps:
  - name: tags
    image: alpine
    commands:
      - sh ./minecraft-bedrock-server/version-tags.sh > .tags

  - name: docker
    image: plugins/docker
    settings:
      context: ./minecraft-bedrock-server
      dockerfile: ./minecraft-bedrock-server/Dockerfile
      repo: 
        from_secret: custom_repo_minecraft_bedrock_server
      registry: 
        from_secret: custom_docker_registry
      username:
        from_secret: custom_docker_username
      password:
        from_secret: custom_docker_password

trigger:
  event:
    - push

---

kind: pipeline
name: minecraft-bedrock-server-cron

steps:
  - name: tags
    image: alpine
    commands:
      - sh ./minecraft-bedrock-server/version-tags.sh > .tags

  - name: docker
    image: plugins/docker
    settings:
      context: ./minecraft-bedrock-server
      dockerfile: ./minecraft-bedrock-server/Dockerfile
      repo:
        from_secret: custom_repo_minecraft_bedrock_server
      registry: 
        from_secret: custom_docker_registry
      username:
        from_secret: custom_docker_username
      password:
        from_secret: custom_docker_password

trigger:
  cron: [ nightly ]

