kind: pipeline
name: filestash

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: awmath/filestash
      context: ./filestash
      dockerfile: ./filestash/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
      - master

---

kind: pipeline
name: filestash-cron

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: awmath/filestash
      context: ./filestash
      dockerfile: ./filestash/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
      - master

trigger:
  cron: [ weekly ]
