kind: pipeline
name: psql-backup

steps:
  - name: docker
    image: plugins/docker
    context: ./psql-backup
    settings:
      repo: awmath/psql-backup
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

---

kind: pipeline
name: psql-backup-cron

steps:
  - name: docker
    image: plugins/docker
    context: ./psql-backup
    settings:
      repo: awmath/psql-backup
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    
trigger:
  cron: [ nightly ]
