kind: pipeline
name: psql-backup

steps:
  - name: docker
    image: plugins/docker
    settings:
      context: ./psql-backup
      dockerfile: ./psql-backup/Dockerfile
      repo: awmath/psql-backup
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - push

---

kind: pipeline
name: psql-backup-cron

steps:
  - name: docker
    image: plugins/docker
    settings:
      context: ./psql-backup
      dockerfile: ./psql-backup/Dockerfile
      repo: awmath/psql-backup
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    
trigger:
  cron: [ nightly ]
