kind: pipeline
name: psql-backup

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: awmath/psql-backup
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    
