kind: pipeline
name: keeweb-http

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: awmath/keeweb-http
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    
