kind: pipeline
name: keeweb-http

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: awmath/keeweb-http
      context: ./keeweb-http
      dockerfile: ./keeweb-http/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    
trigger:
  event:
    - push

---

kind: pipeline
name: keeweb-http-cron

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: awmath/keeweb-http
      context: ./keeweb-http
      dockerfile: ./keeweb-http/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    
trigger:
  cron: [ nightly ]
