name: Build Docker images

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 22 * * 3'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - uses: actions/checkout@v2
      - name: keeweb-http
        uses: docker/build-push-action@v2
        with:
          context: keeweb-http/
          tags: awmath/keeweb-http:latest
      - name: psql-backup
        uses: docker/build-push-action@v2
        with:
          context: psql-backup/
          tags: awmath/psql-backup:latest
      - name: code-server
        uses: docker/build-push-action@v2
        with:
          context: code-server/
          tags: awmath/code-server:latest

  python-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3,3.8]

    steps:
      - uses: actions/checkout@v2
      - name: geopython
        uses: docker/build-push-action@v1
        with:
          path: geopython/
          build_args: VERSION=${{ matrix.python-version }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          repository: awmath/geopython
          tags: latest,${{ matrix.python-version }}

